services:
 db:
  build: 
   context: .
   dockerfile: mysqldockfile

  
  networks:
   - backend

 web:
  image: php:7.4-apache
  ports:
   - 80:80
  depends_on:
   - db
  networks:
   - frontend

 app:
  image: php:7.4-fpm
  depends_on:
   - db
  networks:
   - frontend
   - backend

networks:
  frontend:
  backend:

volumes:
  composevol:
